export { default as About } from "./about/About";
export { default as Hero } from "./hero/Hero";
export { default as Portfolio } from "./portfolio/Portfolio";
export { default as AllProjects } from "./portfolio/AllProjects"
export { default as Members } from "./members/Members";
export { default as Contact } from "./contact/Contact";
export { default as Footer } from "./footer/Footer";
export { default as NotFound } from "./not-found/NotFound";
export { default as FetchError } from "./fetch-error/FetchError"
export { default as Navbar } from "./navbar/Navbar";
